pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/SanRocks1220/CI-CD-Checkpoint.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean install'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
    }
}